# In this notebook, we're going to code some of the most fundamental concepts of tensors using Tensorflow

More specially:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Uing @tf.function(a way to speed up your regular python functions)
* Using GPUs with TensorFlow(or TPU)
* Exercise tyo try for yourself

##Introduction to Tensors

In [ ]:
%cd /content/drive/MyDrive/code/DL/TensorFlow-Developer

/content/drive/MyDrive/code/DL/TensorFlow-Developer


In [ ]:
%pwd

'/content/drive/MyDrive/code/DL/TensorFlow-Developer'

In [2]:
# Import Tensorflow
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor

scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix

matrix = tf.constant([[10,20],
                     [20,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix

another_matrix = tf.constant([[10.,20.],
                              [3.,2.],
                              [5.,5.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 20.],
       [ 3.,  2.],
       [ 5.,  5.]], dtype=float16)>

In [ ]:
# What is the number of dimensions of another_matrix

another_matrix.ndim 

2

In [ ]:
# Let's create a tensor

tensor = tf.constant([[[1,2,3],
                       [2,3,4]],
                       [[3,4,5],
                        [10,22,13]],
                      [[15,45,46],
                       [78,79,75]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 3,  4,  5],
        [10, 22, 13]],

       [[15, 45, 46],
        [78, 79, 75]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar : a single number
* Vector : a number with direction 
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers (when n can be any number, a 0-dimentions tensor s scalar, 1-dimensional tensor is vector)

### Creating tensors with tf.Variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one the elements in our changable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try assign

changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change unchangeable_tensor
unchangeable_tensor[0] = 1
unchangeable_tensor

In [ ]:
unchangeable_tensor[0].assign(1)
unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some abitrary size which contains random numbers

In [ ]:
#create two random(but the same) tensors

random_1 = tf.random.Generator.from_seed(10)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(10)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle the order of element in a tensor

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,20],
                            [45,65],
                            [12,23]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [45, 65],
       [12, 23]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 23],
       [45, 65],
       [10, 20]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 23],
       [45, 65],
       [10, 20]], dtype=int32)>

🗒 https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It looks like if er want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:

>If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [45, 65],
       [12, 23]], dtype=int32)>

Other ways to make tensors

In [ ]:
tf.ones([5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeros

tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

The main difference between NumPy arrays and Tensorflow tensors is that tnesors can be run on a GPU(much faster for numerical computing)

In [ ]:
# you can also turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32 ) # create a NumPy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix
# y = tf.constant(vector) # non-capital for vectors


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2 * 3 * 4

24

In [ ]:
A = tf.constant(numpy_A, shape=(3,8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

In [ ]:
A.ndim

2

In [ ]:
B.ndim

1

### Getting information from thensors

When dealing with tensors you probably want to be aware of the folling attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor(4 dimension)

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor[0][1][1]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
rank_4_tensor[0][1][2][1:]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
# Get various attibutes of tensor
print(f"Data type of every element : {rank_4_tensor.dtype}")
print(f"Number of dimensions (rank) : {rank_4_tensor.ndim}")
print(f"Shape of tensor : {rank_4_tensor.shape}")
print(f"Element along the 0 axis : : {rank_4_tensor.shape[0]}")
print(f"Element along the last axis : : {rank_4_tensor.shape[-1]}")
print("total number of element in our tensor : ",tf.size(rank_4_tensor))
print(f"total number of element in our tensor : {tf.size(rank_4_tensor)}")

Data type of every element : <dtype: 'float32'>
Number of dimensions (rank) : 4
Shape of tensor : (2, 3, 4, 5)
Element along the 0 axis : : 2
Element along the last axis : : 5
total number of element in our tensor :  tf.Tensor(120, shape=(), dtype=int32)
total number of element in our tensor : 120


In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

### Indexing tensors

Tensors can be indexed just like Python lists:

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[0][0][0][0:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimentison from each index except for the final one
rank_4_tensor[ :1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[ :1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[ :1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[ :, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[5,10],
                             [15,20]])

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [ ]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each of our rank 2 tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:, :,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 5],
        [10]],

       [[15],
        [20]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # Expand findal axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 5],
        [10]],

       [[15],
        [20]]], dtype=int32)>

In [ ]:
rank_2_tensor = tf.expand_dims(rank_2_tensor, axis=0)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(1, 1, 2, 2), dtype=int32, numpy=
array([[[[ 5, 10],
         [15, 20]]]], dtype=int32)>

### Manipulating tensor

**Basic operations**

`+`,`-`,`*`,`/`

In [ ]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10,5],[11,12]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [21, 22]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [11, 12]], dtype=int32)>

In [ ]:
tensor = tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 25],
       [31, 32]], dtype=int32)>

In [ ]:
# Multiplication 

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[300, 250],
       [310, 320]], dtype=int32)>

In [ ]:
#Substraction

tensor -5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 20],
       [26, 27]], dtype=int32)>

In [ ]:
# We can use the tensorflow builtin function

tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[150, 125],
       [155, 160]], dtype=int32)>

In [ ]:
tf.add(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 27],
       [33, 34]], dtype=int32)>

In [ ]:
tensor = tf.constant([[1,5],[10,20]])

**Matrix Multiplication**

- In machine Learning, Matrix multiplication ois one of the most common tensor operation

In [ ]:
# Matrix multiplication in tensorflow

print(tensor)

tf.Tensor(
[[ 1  5]
 [10 20]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 51, 105],
       [210, 450]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator "@"

tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 51, 105],
       [210, 450]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a tensor (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrixmultiply 

X@Y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

📖 https://www.mathsisfun.com/algebra/matrix-multiplying.html

**There are two rules our tensor (or matrics) need to fulfil if  we're going to matrix multiply**

- The inner dimension must match
- The resulting matrix has the shape of the outer dimensions

In [ ]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Transpose - flip the Axis
# Reshape shuffle the tensor around into the shape you want

tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The dot product**

Matrix multiplication is also reffered to as the dot product.

You can perform matrix multiplication using
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y transposed) 
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication  between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication  between X and Y (reshaped)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#check the value of Y and transposed Y

print(f"Normal Y : \n{Y}\n")
print(f"Y is reshaped to  : \n{tf.reshape(Y, (2,3))}\n")
print(f"Y is reshaped to  : \n{tf.transpose(Y)}")

Normal Y : 
[[ 7  8]
 [ 9 10]
 [11 12]]

Y is reshaped to  : 
[[ 7  8  9]
 [10 11 12]]

Y is reshaped to  : 
[[ 7  9 11]
 [ 8 10 12]]


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplicaiton  on two tensors and one of the axes doesn't line up , you will transpose (rather than reshape) one of the tensors to get satisfy the matrix muliplication rules.

**Change the datatype of a tensor**

In [ ]:
#Create a new tensor with default datatype(float32)
B = tf.constant([1.5,2.5])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 2.5], dtype=float32)>

In [ ]:
C = tf.constant([10,20])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
# change from float 32 to float 16 (reduce precision)

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 2.5], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float 32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 20.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10., 20.], dtype=float16)>

##**Aggregating tensor**

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values

D = tf.constant([-10,-15])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10, -15], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#creat a random tensor with values betweren 0 abd 100 size of 50
import numpy as np
E = tf.constant(np.random.randint(0,100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([10, 24, 44, 45, 84, 88,  2, 34, 82, 12, 13, 27, 98, 61, 56, 88, 58,
       69, 16, 99, 20, 14, 64, 79, 88, 34, 38, 42, 17, 34, 34, 27,  7, 38,
       99, 63, 58, 63, 73, 43, 65, 92, 24, 64, 33, 60, 51, 95, 24,  0])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
np.min(E)

1

In [ ]:
#find the maximu
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [ ]:
# find the mean
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2641>

**Find the variance and standard deviation**

In [ ]:
#Variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=816>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=816.05634>

In [ ]:
tf.math.reduce_std(E)

TypeError: ignored

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.5667>

**Find the positional maximum and minimum**

In [2]:
# Create a tensor for finding maximum and minimum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F)

42

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
print(f"{F[tf.argmax(F)] == tf.reduce_max(F)}")

True


In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [3]:
#Find the minimum using positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Sq+ueezing a tensor (removing all single dimensions)

In [4]:
# Createtf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [5]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [7]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

### One-Hot encoding tensors

In [9]:
# Create a list of indices

some_list = [0,1,2,3]

#one-hot encode our list of indices

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [12]:
# Secify custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value = "yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

### Squaring , log, square_root

In [13]:
# create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [14]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [16]:
# Find the square root

tf.math.sqrt(H)

InvalidArgumentError: ignored

In [17]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [18]:
# find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensorflow interact beautifly with numPy arrays

In [19]:
# Create a tensor directly from a numpy

J = tf.constant(np.array([1.,2.,3.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [20]:
#Convert our tensor back to Numpy array
np.array(J), type(np.array(J))

(array([1., 2., 3.]), numpy.ndarray)

In [21]:
#Convert tensor J to a NumPy array

J.numpy(), type(J.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [22]:
J = tf.constant([1.])
J.numpy()[0]

1.0

In [23]:
# Default types of each are slightly different

numpy_J = tf.constant(np.array([1.,2.,3.]))
tensor_J = tf.constant([1.,2.,3.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [5]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
! nvidia-smi

Fri Mar 17 07:44:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> 🗒 **note:** If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible